services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: lab-platform-sqlserver
    hostname: lab-platform-sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"

      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"

      MSSQL_DB: "lab_platform"
      MSSQL_USER: "lab_app"
      MSSQL_PASSWORD: "${DB_PASSWORD}"

    ports:
      - "1433:1433"

    volumes:
      - lab-platform-sqlserver-data:/var/opt/mssql

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q \"SELECT 1\" >/dev/null 2>&1 || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

volumes:
  lab-platform-sqlserver-data: